# normally, genesis service is only used in test network, so the default image is for forcenet

version: '3'
services:
  lotus:
    image: tanlang/${NET_TYPE-2k}:nv19
    environment:
      - TZ=${TZ-Asia/Shanghai}
      - LOTUS_API_LISTENADDRESS=/dns/lotus/tcp/1234/http
      - LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/9090
    ports:
      - "1234:1234"
      - "9090:9090"
    env_file:
      - ./chain.env
    volumes:
      - ${proofparameters-/var/tmp/filecoin-proof-parameters/}:/var/tmp/filecoin-proof-parameters/
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ./compose:/compose
    entrypoint: "/compose/scripts/genesis.sh"

  miner:
    image: tanlang/${NET_TYPE-2k}:nv19
    environment:
      - TZ=${TZ-Asia/Shanghai}
      - LOTUS_API_LISTENADDRESS=/dns/lotus/tcp/1234/http
      - LOTUS_LIBP2P_LISTENADDRESSES=/ip4/
